name: wikitoons
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  google_fonts: ^1.1.0
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cartoon.png"

flutter_launcher_name:
  name: "Wikitoons"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit: ^2.2.0
  flare_flutter: ^2.0.6
  flare_splash_screen: ^3.0.1
  page_transition: "^1.1.6"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cartoon.png
    - assets/Television.flr
    - assets/Series60/don_gato.jpg
    - assets/Series60/pantera_rosa.jpg
    - assets/Series60/Picapiedras.jpg
    - assets/Series60/scooby_doo.jpg
    - assets/Series60/supersonicos.jpg
    - assets/Series70/capitan_cavernicola.jpg
    - assets/Series70/dinamita.jpg
    - assets/Series70/mandibulin.jpg
    - assets/Series70/star_trek.jpg
    - assets/Series70/tom_and_jerry.jpg
    - assets/Series80/garfield.jpg
    - assets/Series80/inspecto_gadget.jpg
    - assets/Series80/pitufos.jpg
    - assets/Series80/simpsons.jpg
    - assets/Series80/thundercats.jpg
    - assets/Series80/tortugas_ninja.jpg
    - assets/Series90/animaniacs.jpg
    - assets/Series90/bob_esponja.jpg
    - assets/Series90/catdog.jpg
    - assets/Series90/corage.jpg
    - assets/Series90/dexter_lab.jpg
    - assets/Series90/doug.png
    - assets/Series90/hey_arnold.jpg
    - assets/Series90/recreo.jpg
    - assets/Series90/ppg.jpg
    - assets/Series90/rocko_modern_life.jpg
    - assets/Series90/thornberrys.jpg
    - assets/Series90/rugrats.jpg
    - assets/Series2000/ben10.jpg
    - assets/Series2000/billy_mandy.jpg
    - assets/Series2000/chowder.jpg
    - assets/Series2000/el tigre.jpg
    - assets/Series2000/flapjack.jpg
    - assets/Series2000/jimmy.jpg
    - assets/Series2000/knd.jpg
    - assets/Series2000/lazlo.jpg
    - assets/Series2000/mansion_foster.jpg
    - assets/Series2000/padrinos.jpeg
    - assets/Series2000/samurai_jack.jpg
    - assets/Series2000/timesquad.jpg
    - assets/Series2000/eds.jpg
    - assets/Series2010/adventure_time.jpg
    - assets/Series2010/amphibia.jpg
    - assets/Series2010/ducktales.jpg
    - assets/Series2010/escandalosos.jpg
    - assets/Series2010/gravity_falls.jpg
    - assets/Series2010/gumball.jpg
    - assets/Series2010/harvey beaks.jpg
    - assets/Series2010/infinity_train.jpg
    - assets/Series2010/loud house.jpg
    - assets/Series2010/OK KO.jpg
    - assets/Series2010/otgw.jpg
    - assets/Series2010/owl_house.jpg
    - assets/Series2010/phineasferb.jpg
    - assets/Series2010/regular show.jpg
    - assets/Series2010/STEVEN_UNIVERSE.jpg
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
